# Generated by Django 4.0.6 on 2022-08-12 15:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pack', models.CharField(max_length=300)),
                ('photo_principal', models.ImageField(upload_to='pack')),
                ('photo_1', models.ImageField(blank=True, upload_to='secondary_pack')),
                ('photo_2', models.ImageField(blank=True, upload_to='secondary_pack')),
                ('photo_3', models.ImageField(blank=True, upload_to='secondary_pack')),
                ('photo_4', models.ImageField(blank=True, upload_to='secondary_pack')),
                ('prix_pack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referance_pack', models.CharField(max_length=100)),
                ('description_pack', models.TextField()),
                ('dimension_lonegeur', models.IntegerField()),
                ('dimension_largeur', models.IntegerField()),
                ('moyenne', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_produit', models.ImageField(upload_to='produits')),
                ('statu', models.CharField(choices=[('Sold', 'Sold'), ('Normal', 'Normal')], max_length=50)),
                ('nom_produit', models.CharField(max_length=200)),
                ('referance_produit', models.CharField(max_length=250)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('encien_prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('date_fin_sold', models.DateField(blank=True)),
                ('moyenne', models.IntegerField()),
                ('description', models.TextField()),
                ('dimension_lonegeur', models.IntegerField()),
                ('dimension_largeur', models.IntegerField()),
                ('en_stoke', models.CharField(choices=[('en_stoke', 'en_stoke'), ('out_stock', 'out_stock')], max_length=50)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pub')),
                ('offre', models.IntegerField()),
                ('nom_produit', models.CharField(max_length=250)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comments_pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('comment_text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 8, 12, 16, 10, 59, 556739))),
                ('stars', models.IntegerField()),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('comment_text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 8, 12, 16, 10, 59, 556739))),
                ('stars', models.IntegerField()),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.produit')),
            ],
        ),
        migrations.CreateModel(
            name='command_packs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart_product',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.produit'),
        ),
        migrations.AddField(
            model_name='cart_product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
