# Generated by Django 4.0.6 on 2022-08-13 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_chambre', models.IntegerField()),
                ('dimension_cuisine_longeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jardin', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 17, 46, 38, 531455)),
        ),
        migrations.AlterField(
            model_name='comments_pack',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 13, 17, 46, 38, 531455)),
        ),
    ]
